apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: {NAME}
  namespace: {NAMESPACE}
spec:
  kafka:
    version: 2.4.0
    replicas: 1
    listeners:
      external:
        type: route
        tls: false
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.4"
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
