apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {NAME}
  namespace: {NAMESPACE}
spec:
  kafka:
    version: 2.7.0
    replicas: 1
    listeners:
      # external:
      #   type: route
      #   tls: false
      # plain: {}
      # tls: {}
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    - name: external
      port: 9094
      type: route
      tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.7"
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
