apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {NAME}
  namespace: {NAMESPACE}
spec:
  kafka:
    version: 2.7.0
    replicas: {REPLICAS}
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: {AUTH_TYPE}
    config:
      offsets.topic.replication.factor: {REPLICAS}
      transaction.state.log.replication.factor: {REPLICAS}
      transaction.state.log.min.isr: {MIN_ISR}
      log.message.format.version: "2.7"
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
