name: Apicurio Registry Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  tests:
    name: Kubernetes Tests
    runs-on: ubuntu-latest
    env:
      CI_MESSAGE_HEADER: Registry ${{ matrix.test_profile }} Tests
    strategy:
      fail-fast: false
      matrix:
        test_profile: [smoke, acceptance, serdes] #, upgrade]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64

      - name: Kubernetes Tests
        run:  E2E_APICURIO_TESTS_PROFILE=${{ matrix.test_profile }} ./.github/scripts/test_apicurio_kubernetes.sh

      - name: Collect logs
        if: failure()
        run: TEST_ID=${{ matrix.test_profile }} ./.github/scripts/collect_kubernetes_logs.sh

      - name: Upload tests logs artifacts
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: tests-logs
          path: artifacts

      # - name: Send CI message
      #   if: github.event_name == 'schedule'
      #   env:
      #     CI_MESSAGES_ENDPOINT: ${{ secrets.CI_MESSAGES_ENDPOINT }}
      #   run: make send-ci-message