name: Apicurio Registry Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours

jobs:
  tests:
    name: Apicurio Registry Tests
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        test_profile: [smoke, acceptance, cluster, ui, all]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '8'
          architecture: x64

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Kubernetes Tests
        run:  E2E_APICURIO_TESTS_PROFILE=${{ matrix.test_profile }} ./.github/scripts/test_apicurio_kubernetes.sh

      - name: Collect logs
        if: failure()
        run: TEST_ID=${{ matrix.test_profile }} ./.github/scripts/collect_kubernetes_logs.sh

      - name: Upload tests logs artifacts
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: tests-logs
          path: artifacts
          
