name: Apicurio Registry Kubernetes Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Apicurio Registry Kubernetes Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '8'
          architecture: x64

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Kubernetes Tests
        run: ./.github/scripts/test_apicurio_kubernetes.sh

      - name: Collect logs
        if: failure()
        run: ./.github/scripts/collect_kubernetes_logs.sh

      - name: Upload tests logs artifacts
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: tests-logs
          path: artifacts
          
