name: Apicurio Registry Operator Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  tests:
    name: Kubernetes Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
 
      - name: Kubernetes Tests
        run: ./.github/scripts/test_operator.sh

      - name: Collect logs
        if: failure()
        run: TEST_ID=operator ./.github/scripts/collect_kubernetes_logs.sh

      - name: Upload tests logs artifacts
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: tests-logs
          path: artifacts

      - name: Send CI message
        if: github.event_name == 'schedule' || github.event_name == 'push'
        env:
          CI_MESSAGE_HEADER: Operator scheduled Tests
          CI_MESSAGES_ENDPOINT: ${{ secrets.CI_MESSAGES_ENDPOINT }}
        run: make send-ci-message
