name: Apicurio Registry Operator Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Kubernetes Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
 
      - name: Kubernetes Tests
        run: ./.github/scripts/test_operator.sh

      - name: Collect logs
        if: failure()
        run: TEST_ID=operator ./.github/scripts/collect_kubernetes_logs.sh

      - name: Upload tests logs artifacts
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: tests-logs
          path: artifacts
          
